name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part:
          - part_number_1
          - part_number_2
          - part_number_3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Execute commands for ${{ matrix.part }}
        run: |
          echo "Processing ${matrix.part}"
          # Example of random commands
          echo "Listing files in the current directory:"
          ls -la
          echo "Displaying current date and time:"
          date
          echo "Creating a file named ${matrix.part}.txt"
          touch ${matrix.part}.txt
          echo "Writing some content to ${matrix.part}.txt"
          echo "This is a file for ${matrix.part}" > ${matrix.part}.txt
          echo "Displaying the content of ${matrix.part}.txt"
          cat ${matrix.part}.txt
