name: Dynamic Matrix Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create elements.txt file
      run: |
        echo -e "element1\nelement2\nelement3" > elements.txt

    - name: List files in the current directory
      run: ls -al

    - name: Read elements from file
      id: read-file
      run: |
        # Read the file and store elements in an array
        elements=($(cat elements.txt))
        # Convert the array to a JSON array
        elements_json=$(printf '%s\n' "${elements[@]}" | jq -R . | jq -s .)
        echo "Elements JSON: $elements_json"
        # Escape the JSON array for environment file
        elements_json_escaped=$(echo $elements_json | jq -c .)
        echo "MATRIX=$elements_json_escaped" >> $GITHUB_ENV

    - name: Set matrix output
      id: set-matrix
      run: echo "Matrix set"
      env:
        matrix: ${{ env.MATRIX }}
      outputs:
        matrix: ${{ env.MATRIX }}

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        element: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute code for element
      run: |
        echo "Executing code for element: ${{ matrix.element }}"
        # Replace the following line with the actual code execution
        echo "Running code for ${{ matrix.element }}..."
        # Simulate code execution
        sleep 5
        echo "Completed code execution for ${{ matrix.element }}"

    - name: Report progress
      run: |
        echo "Job for ${{ matrix.element }} completed."
