name: Dynamic Matrix Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the .github/workflows directory
      run: ls -al .github/workflows

    - name: Read elements from file
      id: read-file
      run: |
        # Read the file and store elements in an array
        elements=($(cat .github/workflows/elements.txt))
        # Convert the array to a JSON array
        elements_json=$(printf '%s\n' "${elements[@]}" | jq -R . | jq -s .)
        echo "Elements JSON: $elements_json"
        # Save the JSON array to an environment file
        echo "matrix=$elements_json" >> $GITHUB_ENV

    - name: Set matrix
      id: set-matrix
      run: echo "Matrix: ${{ env.matrix }}"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        element: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute code for element
      run: |
        echo "Executing code for element: ${{ matrix.element }}"
        # Replace the following line with the actual code execution
        echo "Running code for ${{ matrix.element }}..."
        # Simulate code execution
        sleep 5
        echo "Completed code execution for ${{ matrix.element }}"

    - name: Report progress
      run: |
        echo "Job for ${{ matrix.element }} completed."
