# .github/workflows/process_files.yml
name: Process Files

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      elements: ${{ steps.get-elements.outputs.elements }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script to get elements
      id: get-elements
      run: |
        python scripts/example_script.py input/input.txt
        elements=$(cat elements.txt | jq -R -s -c 'split("\n")[:-1]')
        echo "elements=$elements" >> $GITHUB_ENV
      outputs:
        elements: ${{ steps.get-elements.outputs.elements }}

  process:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        element: ${{ fromJson(needs.prepare.outputs.elements) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create output directory
      run: mkdir -p output

    - name: Process element
      run: |
        echo "Processing element: ${{ matrix.element }}"
        output_file="output/output_${{ matrix.element }}.json"
        echo '{"part_number": "'${{ matrix.element }}'"}' > $output_file

    - name: Upload output file
      uses: actions/upload-artifact@v4
      with:
        name: output-${{ matrix.element }}
        path: output/output_${{ matrix.element }}.json
